apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: banking

resources:
  - ../../base

patchesStrategicMerge:
  - patch-account-service.yaml
  - patch-transaction-service.yaml
  - patch-audit-service.yaml
  - patch-api-gateway.yaml
  - patch-frontend.yaml
  - patch-api-gateway-service.yaml
  - patch-frontend-service.yaml
  - patch-delete-ingress.yaml
