server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: com.example.shared.model
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:transactiondb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  data:
    cassandra:
      contact-points: ${SPRING_DATA_CASSANDRA_CONTACT_POINTS:cassandra}
      port: ${SPRING_DATA_CASSANDRA_PORT:9042}
      keyspace-name: ${SPRING_DATA_CASSANDRA_KEYSPACE:banking}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
banking:
  topics:
    transaction: banking-transactions
accounts:
  service:
    url: http://localhost:8081
logging:
  level:
    org.springframework: INFO
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
