apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
data:
  POSTGRES_DB: banking
  POSTGRES_USER: banking
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  ACCOUNT_SERVICE_URL: http://account-service:8081
  TRANSACTION_SERVICE_URL: http://transaction-service:8082
  AUDIT_SERVICE_URL: http://audit-service:8084
  ACCOUNTS_SERVICE_URL: http://account-service:8081
  BANKING_TOPICS_TRANSACTION: banking-transactions
